import type { Product } from "../backend.d";

export const mockProducts: Product[] = [
  {
    id: "1",
    title: "AirMax Pro Elite",
    originalPrice: 249.99,
    price: 179.99,
    description:
      "Next-generation athletic footwear engineered for peak performance. Features responsive cushioning technology, breathable mesh upper, and carbon fiber reinforced sole for maximum energy return.",
    sizes: ["7", "8", "9", "10", "11", "12"],
    stock: 50n,
    category: "Sports",
    rating: 4.9,
    colors: ["#000000", "#FFFFFF", "#2FD4FF"],
    reviewCount: 342n,
    isFlashSale: true,
    isTrending: true,
    images: [],
  },
  {
    id: "2",
    title: "Wireless Pro Headphones X7",
    originalPrice: 399.99,
    price: 299.99,
    description:
      "Studio-grade wireless headphones with 40-hour battery life, active noise cancellation, and Hi-Res Audio certification. Premium leather earcups for all-day comfort.",
    sizes: ["One Size"],
    stock: 30n,
    category: "Electronics",
    rating: 4.8,
    colors: ["#1a1a1a", "#C0C0C0", "#8B4513"],
    reviewCount: 289n,
    isFlashSale: true,
    isTrending: true,
    images: [],
  },
  {
    id: "3",
    title: "Urban Street Jacket",
    originalPrice: 189.99,
    price: 149.99,
    description:
      "Premium waterproof street jacket with tech fabric blend. Features concealed hood, magnetic closures, and reflective piping for night visibility.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    stock: 45n,
    category: "Fashion",
    rating: 4.7,
    colors: ["#1a1a1a", "#2d4a6e", "#8B4513"],
    reviewCount: 156n,
    isFlashSale: false,
    isTrending: true,
    images: [],
  },
  {
    id: "4",
    title: "Smart Watch Ultra Series 5",
    originalPrice: 549.99,
    price: 449.99,
    description:
      "The most advanced smartwatch ever. Always-on AMOLED display, health monitoring suite, GPS, and titanium case. Tracks 100+ workout types.",
    sizes: ["40mm", "44mm", "49mm"],
    stock: 20n,
    category: "Electronics",
    rating: 4.9,
    colors: ["#1a1a1a", "#C0C0C0", "#FFD700"],
    reviewCount: 521n,
    isFlashSale: false,
    isTrending: true,
    images: [],
  },
  {
    id: "5",
    title: "Luxury Sofa Collection - Oslo",
    originalPrice: 2499.99,
    price: 1899.99,
    description:
      "Scandinavian-inspired modular sofa with premium full-grain leather upholstery. Deep seat cushions with memory foam, solid oak legs, and whisper-quiet reclining mechanism.",
    sizes: ["2-Seater", "3-Seater", "L-Shape"],
    stock: 8n,
    category: "Home",
    rating: 4.8,
    colors: ["#8B7355", "#2F4F4F", "#1a1a1a"],
    reviewCount: 89n,
    isFlashSale: false,
    isTrending: false,
    images: [],
  },
  {
    id: "6",
    title: "Glow Serum Radiance Kit",
    originalPrice: 129.99,
    price: 89.99,
    description:
      "Celebrity-endorsed skincare collection with vitamin C brightening serum, hyaluronic acid moisturizer, and retinol night cream. Clinically tested for all skin types.",
    sizes: ["30ml", "50ml", "Kit"],
    stock: 100n,
    category: "Beauty",
    rating: 4.6,
    colors: ["#FFD700", "#FFC0CB", "#FFFFFF"],
    reviewCount: 423n,
    isFlashSale: true,
    isTrending: true,
    images: [],
  },
  {
    id: "7",
    title: "Carbon Pro Running Shoes",
    originalPrice: 219.99,
    price: 169.99,
    description:
      "Professional marathon shoes with carbon fiber plate technology. Delivers 40% more energy return with each stride. Used by elite runners worldwide.",
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
    stock: 60n,
    category: "Sports",
    rating: 4.8,
    colors: ["#FF4500", "#1a1a1a", "#00CED1"],
    reviewCount: 267n,
    isFlashSale: true,
    isTrending: false,
    images: [],
  },
  {
    id: "8",
    title: "Architect Table Lamp - Noir",
    originalPrice: 189.99,
    price: 159.99,
    description:
      "Minimalist architectural desk lamp with adjustable articulating arm, dimmer control, and warm/cool light modes. Premium brushed brass finish.",
    sizes: ["Standard"],
    stock: 35n,
    category: "Home",
    rating: 4.7,
    colors: ["#FFD700", "#1a1a1a", "#FFFFFF"],
    reviewCount: 112n,
    isFlashSale: false,
    isTrending: true,
    images: [],
  },
  {
    id: "9",
    title: "Premium Leather Sneaker",
    originalPrice: 299.99,
    price: 249.99,
    description:
      "Handcrafted Italian leather sneaker with vintage-inspired silhouette. Full-grain leather upper, cushioned insole, and vulcanized rubber outsole.",
    sizes: ["7", "8", "9", "10", "11", "12"],
    stock: 25n,
    category: "Fashion",
    rating: 4.9,
    colors: ["#FFFFFF", "#000000", "#8B4513"],
    reviewCount: 198n,
    isFlashSale: false,
    isTrending: true,
    images: [],
  },
  {
    id: "10",
    title: '4K OLED Monitor 32"',
    originalPrice: 1299.99,
    price: 999.99,
    description:
      "Professional 32-inch OLED display with 4K resolution, 120Hz refresh rate, and 99% DCI-P3 color coverage. Perfect for creative professionals and gamers.",
    sizes: ['27"', '32"'],
    stock: 15n,
    category: "Electronics",
    rating: 4.9,
    colors: ["#1a1a1a"],
    reviewCount: 387n,
    isFlashSale: true,
    isTrending: false,
    images: [],
  },
  {
    id: "11",
    title: "Yoga Performance Set",
    originalPrice: 119.99,
    price: 89.99,
    description:
      "High-performance yoga set with moisture-wicking leggings and sports bra. Four-way stretch fabric maintains shape through any pose. Pockets included.",
    sizes: ["XS", "S", "M", "L", "XL"],
    stock: 80n,
    category: "Sports",
    rating: 4.6,
    colors: ["#000000", "#8B0000", "#2F4F4F"],
    reviewCount: 315n,
    isFlashSale: false,
    isTrending: true,
    images: [],
  },
  {
    id: "12",
    title: "Hydra Luminous Foundation",
    originalPrice: 79.99,
    price: 59.99,
    description:
      "Long-wear luminous foundation with SPF 30 and hydrating hyaluronic acid complex. 40 inclusive shades, 24-hour wear without touch-ups.",
    sizes: ["N10", "N20", "N30", "N40"],
    stock: 120n,
    category: "Beauty",
    rating: 4.5,
    colors: ["#F5CBA7", "#DC9F79", "#A0522D"],
    reviewCount: 634n,
    isFlashSale: false,
    isTrending: false,
    images: [],
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Sarah Mitchell",
    role: "Fashion Designer",
    avatar: "SM",
    rating: 5,
    quote:
      "LUXE has completely transformed my shopping experience. The quality of every product I've ordered has exceeded my expectations. Fast delivery, premium packaging.",
  },
  {
    id: 2,
    name: "James Rodriguez",
    role: "Fitness Coach",
    avatar: "JR",
    rating: 5,
    quote:
      "The AirMax Pro Elite sneakers are absolutely incredible. I wear them for every training session and they still look and feel brand new after 6 months of intense use.",
  },
  {
    id: 3,
    name: "Priya Sharma",
    role: "Tech Entrepreneur",
    avatar: "PS",
    rating: 5,
    quote:
      "Finally, a store that understands premium quality. The Smart Watch Ultra has become my most used device. Customer service is outstanding as well.",
  },
];
