/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'color' : [] | [string],
  'size' : [] | [string],
  'productId' : string,
  'quantity' : bigint,
}
export interface OrderType {
  'id' : string,
  'status' : { 'shipped' : null } |
    { 'pending' : null } |
    { 'delivered' : null } |
    { 'processing' : null },
  'total' : number,
  'userId' : Principal,
  'shippingAddress' : string,
  'items' : Array<CartItem>,
}
export interface Product {
  'id' : string,
  'title' : string,
  'originalPrice' : number,
  'description' : string,
  'sizes' : Array<string>,
  'stock' : bigint,
  'category' : string,
  'rating' : number,
  'colors' : Array<string>,
  'price' : number,
  'reviewCount' : bigint,
  'isFlashSale' : boolean,
  'isTrending' : boolean,
  'images' : Array<string>,
}
export interface Review {
  'userId' : Principal,
  'productId' : string,
  'comment' : string,
  'rating' : bigint,
}
export interface UserProfile { 'displayName' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReview' : ActorMethod<[string, bigint, string], undefined>,
  'addToCart' : ActorMethod<[CartItem], undefined>,
  'addToWishlist' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCoupon' : ActorMethod<[string, bigint], undefined>,
  'createOrUpdateProduct' : ActorMethod<[Product], undefined>,
  'createOrder' : ActorMethod<[string, string], undefined>,
  'filterProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'filterProductsByPriceRange' : ActorMethod<[number, number], Array<Product>>,
  'getAllOrders' : ActorMethod<[], Array<OrderType>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getCallerCart' : ActorMethod<[], [] | [Array<CartItem>]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerWishlist' : ActorMethod<[], [] | [Array<string>]>,
  'getCart' : ActorMethod<[Principal], [] | [Array<CartItem>]>,
  'getOrder' : ActorMethod<[string], [] | [OrderType]>,
  'getProduct' : ActorMethod<[string], Product>,
  'getProductReviews' : ActorMethod<[string], Array<Review>>,
  'getUserOrders' : ActorMethod<[Principal], Array<OrderType>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[Principal], [] | [Array<string>]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'removeFromWishlist' : ActorMethod<[string], undefined>,
  'reseedProducts' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCartItem' : ActorMethod<[string, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<
    [
      string,
      { 'shipped' : null } |
        { 'pending' : null } |
        { 'delivered' : null } |
        { 'processing' : null },
    ],
    undefined
  >,
  'validateCoupon' : ActorMethod<[string], [] | [bigint]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];