/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CartItem = IDL.Record({
  'color' : IDL.Opt(IDL.Text),
  'size' : IDL.Opt(IDL.Text),
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'originalPrice' : IDL.Float64,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'stock' : IDL.Nat,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'colors' : IDL.Vec(IDL.Text),
  'price' : IDL.Float64,
  'reviewCount' : IDL.Nat,
  'isFlashSale' : IDL.Bool,
  'isTrending' : IDL.Bool,
  'images' : IDL.Vec(IDL.Text),
});
export const OrderType = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'shipped' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  }),
  'total' : IDL.Float64,
  'userId' : IDL.Principal,
  'shippingAddress' : IDL.Text,
  'items' : IDL.Vec(CartItem),
});
export const Review = IDL.Record({
  'userId' : IDL.Principal,
  'productId' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'addToCart' : IDL.Func([CartItem], [], []),
  'addToWishlist' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createCoupon' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'createOrUpdateProduct' : IDL.Func([Product], [], []),
  'createOrder' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'filterProductsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'filterProductsByPriceRange' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderType)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getCallerCart' : IDL.Func([], [IDL.Opt(IDL.Vec(CartItem))], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWishlist' : IDL.Func([], [IDL.Opt(IDL.Vec(IDL.Text))], ['query']),
  'getCart' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Vec(CartItem))],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(OrderType)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProductReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(OrderType)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWishlist' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Vec(IDL.Text))],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromCart' : IDL.Func([IDL.Text], [], []),
  'removeFromWishlist' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCartItem' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateOrderStatus' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'shipped' : IDL.Null,
          'pending' : IDL.Null,
          'delivered' : IDL.Null,
          'processing' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'validateCoupon' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CartItem = IDL.Record({
    'color' : IDL.Opt(IDL.Text),
    'size' : IDL.Opt(IDL.Text),
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'originalPrice' : IDL.Float64,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'stock' : IDL.Nat,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'colors' : IDL.Vec(IDL.Text),
    'price' : IDL.Float64,
    'reviewCount' : IDL.Nat,
    'isFlashSale' : IDL.Bool,
    'isTrending' : IDL.Bool,
    'images' : IDL.Vec(IDL.Text),
  });
  const OrderType = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'shipped' : IDL.Null,
      'pending' : IDL.Null,
      'delivered' : IDL.Null,
      'processing' : IDL.Null,
    }),
    'total' : IDL.Float64,
    'userId' : IDL.Principal,
    'shippingAddress' : IDL.Text,
    'items' : IDL.Vec(CartItem),
  });
  const Review = IDL.Record({
    'userId' : IDL.Principal,
    'productId' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'addToCart' : IDL.Func([CartItem], [], []),
    'addToWishlist' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createCoupon' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'createOrUpdateProduct' : IDL.Func([Product], [], []),
    'createOrder' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'filterProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'filterProductsByPriceRange' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderType)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getCallerCart' : IDL.Func([], [IDL.Opt(IDL.Vec(CartItem))], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWishlist' : IDL.Func([], [IDL.Opt(IDL.Vec(IDL.Text))], ['query']),
    'getCart' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Vec(CartItem))],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(OrderType)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProductReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getUserOrders' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(OrderType)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWishlist' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Vec(IDL.Text))],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromCart' : IDL.Func([IDL.Text], [], []),
    'removeFromWishlist' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCartItem' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateOrderStatus' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'shipped' : IDL.Null,
            'pending' : IDL.Null,
            'delivered' : IDL.Null,
            'processing' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'validateCoupon' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };